# Generated by Django 4.2.7 on 2023-12-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('Мягкий', 'Мягкий'), ('Твердый', 'Твердый')], max_length=16)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('place_amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantplace',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='restaurantplace',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='restaurantplace',
            name='number',
        ),
        migrations.RemoveField(
            model_name='restaurantplace',
            name='place_amount',
        ),
        migrations.RemoveField(
            model_name='restaurantplace',
            name='type',
        ),
        migrations.AlterField(
            model_name='restaurantplace',
            name='booked_on',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurantplace',
            name='occupied_in',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='restaurantplace',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restauranttable'),
            preserve_default=False,
        ),
    ]
