# Generated by Django 4.2.7 on 2023-12-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restauranttable_remove_restaurantplace_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='table_size',
            field=models.CharField(choices=[('Маленький', 'table-small'), ('Средний', 'table-medium'), ('Большой', 'table-large')], default='table-small', max_length=16),
            preserve_default=False,
        ),
    ]
