# Generated by Django 4.2.7 on 2023-12-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restauranttable_table_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='table_size',
            field=models.CharField(choices=[('Маленький', 'table-small'), ('Средний', 'table-medium'), ('Большой', 'table-large'), ('Средний (вертикальный)', 'table-medium-vertical'), ('Большой (вертикальный)', 'table-large-vertical')], max_length=32),
        ),
    ]
