# Generated by Django 4.2.7 on 2023-12-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurantplace_booked_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantplace',
            name='table',
        ),
        migrations.AddField(
            model_name='restaurantplace',
            name='local_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurantplace',
            name='location_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurantplace',
            name='location_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurantplace',
            name='place_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurantplace',
            name='table_size',
            field=models.CharField(choices=[('table-small', 'Маленький'), ('table-medium', 'Средний'), ('table-large', 'Большой'), ('table-medium-vertical', 'Средний (вертикальный)'), ('table-large-vertical', 'Большой (вертикальный)')], default='table-small', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantplace',
            name='type',
            field=models.CharField(choices=[('Мягкий', 'Мягкий'), ('Твердый', 'Твердый')], default='Мягкий', max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RestaurantTable',
        ),
    ]
