# Generated by Django 4.2.7 on 2023-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_restaurantplace_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantplace',
            name='booked_on',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantplace',
            name='occupied_in',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
