# Generated by Django 4.2.7 on 2023-12-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='working_mode',
            field=models.TextField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
