# Generated by Django 4.2.7 on 2023-12-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_working_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreview',
            name='mark',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')]),
        ),
    ]
