# Generated by Django 4.2.7 on 2023-12-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurantmeal_image_delete_mealimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmeal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/%Y/%m/%d/'),
        ),
    ]
